In [2]:
import tensorflow as tf

p=tf.constant([3.33,2.0,3.5,4.6],shape=[1,4],name='x')
q=tf.constant([4.55,7.5,7.0,8.5],shape=[1,4],name='y')

with tf.name_scope("mean"):
    with tf.name_scope("mean_x_y"):
        x1=tf.reduce_mean(p)
        y1=tf.reduce_mean(q)
        sess=tf.Session()
        print("mean p")
    print(sess.run(x1))
    print("mean q")
    print(sess.run(y1))
   
with tf.name_scope("variance"):
    with tf.name_scope("scope_sub1"):
        a=tf.subtract(p,x1)
        sess1=tf.Session()
    print(sess1.run(a))
    with tf.name_scope("scope_sub2"):
        b=tf.subtract(q,y1)
        sess2=tf.Session()
    print(sess2.run(b))
    with tf.name_scope("scope_square"):
        a1=tf.multiply(a,a)
        sess3=tf.Session()
    print(sess3.run(a1))
    with tf.name_scope("scope_summation"):
        var=tf.reduce_sum(a1)
        sess4=tf.Session()
        print("variance")
    print(sess4.run(var))
   
with tf.name_scope("covariance"):
    with tf.name_scope("multiplication"):
        mul1=tf.multiply(p,q)
        sess5=tf.Session()
    print(sess5.run(mul1))
    with tf.name_scope("scope_summation2"):
        covar=tf.reduce_sum(mul1)
        sess6=tf.Session()
        print("covarience")
    print(sess6.run(covar))


mean p
3.3575
mean q
6.8875
[[-0.02750015 -1.35750008  0.14249992  1.24249983]]
[[-2.33749962  0.61250019  0.11250019  1.61250019]]
[[  7.56258378e-04   1.84280646e+00   2.03062277e-02   1.54380584e+00]]
variance
3.40767
[[ 15.1515007   15.          24.5         39.09999847]]
covarience
93.7515


In [3]:
import tensorflow as tf
x=tf.constant(7)
y=tf.constant(5)
with tf.name_scope("MyOperationGroup"):
    with tf.name_scope("Scope_A"):
        a = tf.multiply(x,x)
        b = tf.multiply(y,y)
with tf.name_scope("Scope_B"):
    c = tf.add(a, b, name="And_These_ones")
    d = tf.multiply(x, y, name="Multiply_these_numbers")

with tf.name_scope("Scope_C"):
    e = tf.multiply(2, d, name="B_add")

g = tf.subtract(c,e)

with tf.Session() as sess:
    writer = tf.summary.FileWriter("/tmp/tboard/output_3", sess.graph)
    print(sess.run(g))
    writer.close()

4


In [4]:
import tensorflow as tf
x=tf.constant(4)
y=tf.constant(2)
with tf.name_scope("MyOperationGroup"):
    with tf.name_scope("Scope_A"):
        a = tf.multiply(x,x)
        b = tf.multiply(y,y) 
with tf.name_scope("Scope_B"):
    c = tf.add(a, b, name="And_These_ones")
    d = tf.multiply(x, y, name="Multiply_these_numbers")

with tf.name_scope("Scope_C"):
    e=tf.subtract(c,d, name="subtrating")
    f=tf.add(x,y)
  
with tf.name_scope("Scope_D"):
    g = tf.multiply(f,e)


with tf.Session() as sess:
    writer = tf.summary.FileWriter("/tmp/tboard/output_1", sess.graph)
    print(sess.run(g))
    writer.close()

72
